services:
  shortener-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shortener
    ports:
      - "3001:5432"
    volumes:
      - shortener-db-data:/var/lib/postgresql/data
    networks:
      - shortener-network
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

    networks:
      - shortener-network
  # shortener-app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - shortener-db
  #     - redis
  #   networks:
  #     - shortener-network
volumes:
  shortener-db-data:
networks:
  shortener-network: