services:
  shortener-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shortener_db
    ports:
      - "3001:5432"
    volumes:
      - shortener-db-data:/var/lib/postgresql/data
    networks:
      - shortener-network
  redis:
    image: redis:7-alpine
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --maxmemory
      - 256mb
      - --maxmemory-policy
      - volatile-lru
    ports:
      - "6379:6379"
    volumes:
      - shortener-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - shortener-network
  # shortener-app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - shortener-db
  #     - redis
  #   networks:
  #     - shortener-network
volumes:
  shortener-db-data:
  shortener-redis-data:
networks:
  shortener-network:
